### PR TITLE
Update update-nft-metadata.md

### PR DESCRIPTION
**Pull request by MilanWR**
**Description**:
TokenUpdateNftsTransaction doesn't exist in the sdk, it's TokenNftsUpdateTransaction

Signed-off-by: MilanWR

### CODE REVIEW

**Comment by MilanWR** [comment]
I have no idea what this DCO thing is

**Comment by SimiHunjan** [comment]
@MilanWR this would point you to the steps to resolve DCO: https://github.com/hashgraph/hedera-docs/pull/663/checks?check_run_id=24904086031

In general you have to add this to your commit message: Signed-off-by: Author Name <authoremail@example.com>

**Comment by MilanWR** [comment]
thank you @SimiHunjan , do I need to create a new pull request?

**Review by theekrystallee — APPROVED** [review]
@MilanWR thanks for the PR! Looks good. 

I'll approve and merge this one. For future PRs, please sign off on your commit messages.

**Comment by MilanWR** [comment]
@theekrystallee this change should be reverted, as TokenUpdateNftsTransaction now exists in the SDK and TokenNftsUpdateTransaction is removed. (no idea how i reopen this)

**Comment by theekrystallee** [comment]
@MilanWR thanks for the ping. you dont have to reopen, I can make the changes and revert back. thanks again!

**Comment by MilanWR** [comment]
thanks @theekrystallee !

**Pull request merged**
