### PR TITLE
docs: HW seq for HTS fungible token

### PR DESCRIPTION
**Pull request by bguiz**
**Description**:

## What

- Add new Hello World sequence for HTS fungible token

## Why

- Next in series of Hello World sequences

**Related issue(s)**:

- Preview PR: https://github.com/hedera-dev/preview-hedera-docs/pull/7
- Parent: https://github.com/hashgraph/hedera-docs/issues/485

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
  - `npm run test`

### CODE REVIEW

**Comment by bguiz** [comment]
Updated preview: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/8IZNeYRVmKS7DilAixtH/
@theekrystallee I intend to resolve the merge conflict after your review

**Comment by theekrystallee** [comment]
Will approve and merge once conflicts are resolved. Thanks

**Comment by bguiz** [comment]
@theekrystallee Resolved merge conflicts and added author cards
update preview: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/JbWQoC2K99cmQo9FY6m2/tutorials/hello-world/hts-fungible-token

**Review by theekrystallee — APPROVED** [review]
Looks good. Thank you

**Pull request merged**
