### PR TITLE
doc: HW seq for HSCS smart contract

### PR DESCRIPTION
**Pull request by bguiz**
**Description**:

## What

- Add new Hello World sequence for HSCS smart contract

## Why

- Next in series of Hello World sequences

**Related issue(s)**:

- Preview PR: https://github.com/hedera-dev/preview-hedera-docs/pull/5
- Parent: https://github.com/hashgraph/hedera-docs/issues/485

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
  - `npm run test`

### CODE REVIEW

**Comment by bguiz** [comment]
Updated preview: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/ALUEr1YK7B9SrDf60UkA/tutorials/hello-world/hscs-smart-contract

**Review by theekrystallee — DISMISSED** [review]
Thanks for the PR and resolving the conflicts. Looks good

**Comment by theekrystallee** [comment]
Sorry, there was an update to the README. Please resolve the conflict so we can merge.

**Review by theekrystallee — APPROVED** [review]
Looks good.

**Comment by bguiz** [comment]
In terms of how this could be designed into the UI, I do like the way that [`iancoleman.io/bip39`](https://iancoleman.io/bip39/) does it, where if you click on a field it toggles the visibility of the QR code in the corner.
image

(The same site also toggles upon mouse hover, but I'm not a fan, as it tends to result in a bunch of "flicker")

**Pull request merged**
