### PR TITLE
Update hcs-submit-your-first-message.md

### PR DESCRIPTION
**Pull request by adrian-scehura**
Hello :D

From 1.2.0 version 

```java
   new ConsensusMessageSubmitTransaction()
        .setTopicId(topicId)
        .setMessage("hello, HCS! ")
        .execute(client);
```
returns `List<TransactionId>`.

### CODE REVIEW

**Comment by Cooper-Kunz** [comment]
Hey @adian thanks for the PR!

@SimiHunjan are you able to review & see what functionality we want in the tutorial? 

It feels like maybe we should break out getting the transaction ID and fetch the receipt separately to be extra clear.

**Comment by SimiHunjan** [comment]
hey @adian thanks for the PR :D. Will review as soon as we get testnet up and running.

**Comment by SimiHunjan** [comment]
hey @adian were you looking get the transaction ID and fetch the receipt to verify the message submit transaction reached consensus as below?

```java
        //Submit a message to a topic
        final List<TransactionId> messageTransactionId = new ConsensusMessageSubmitTransaction()
                .setTopicId(topicId)
                .setMessage("hello, HCS! ")
                .execute(client);

        System.out.println("The transaction ID is " +messageTransactionId);

        Status receipt = messageTransactionId.get(0).getReceipt(client).status;

        System.out.println("The transaction result " +receipt);
```

**Comment by adrian-scehura** [comment]
@SimiHunjan I don't really get what you mean. Can you explain it? :D

**Comment by SimiHunjan** [comment]
hey @adian instead of getting the transaction receipt in one step, the transaction ID for the message is returned first (`messageTransactionId)`. Then separately the receipt is requested (`receipt`).

**Review by SimiHunjan — APPROVED** [review]

**Pull request merged**
