### PR TITLE
Added option for Java Maven project

### PR DESCRIPTION
**Pull request by fabianstraubinger99**
Added a new tab for Maven
Renamed title for Java to Java Gradle

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by theekrystallee — APPROVED** [review]
Thanks so much for the PR! This looks great.

**Comment by theekrystallee** [comment]
If you want us to add credit for this contribution, can you send me the name (or username) and preferred social media (e.g., GitHub, Twitter) you want to add to the page?

For example, this is how it will appear at the end of the page you contributed to:

> **Contributor**: **[Fabian](https://github.com/fabianstraubinger99)**

or

>  **Contributor**: **[fabianstraubinger99](https://github.com/fabianstraubinger99)**

**Comment by fabianstraubinger99** [comment]
> If you want us to add credit for this contribution, can you send me the name (or username) and preferred social media (e.g., GitHub, Twitter) you want to add to the page?
> 
> For example, this is how it will appear at the end of the page you contributed to:
> 
> > **Contributor**: **[Fabian](https://github.com/fabianstraubinger99)**
> 
> or
> 
> > **Contributor**: **[fabianstraubinger99](https://github.com/fabianstraubinger99)**

Hello, I would be very pleased with the lower variant.

**Comment by theekrystallee** [comment]
Done! Thanks again so much for contributing to our documentation :) 

https://docs.hedera.com/hedera/getting-started/environment-set-up

**Pull request merged**
