### PR TITLE
Update specialized-types.md

### PR DESCRIPTION
**Pull request by MilanWR**
AccountId.fromSolidityAddress is deprecated, use fromEvmAddress instead

Signed-off-by: MilanWR <milan@8bees.fr>

### CODE REVIEW

**Comment by theekrystallee** [comment]
@MilanWR can you please [resolve DCO](https://github.com/hashgraph/hedera-docs/pull/683/checks?check_run_id=25241804090) and resubmit? Thanks!

**Comment by MilanWR** [comment]
> @MilanWR can you please [resolve DCO](https://github.com/hashgraph/hedera-docs/pull/683/checks?check_run_id=25241804090) and resubmit? Thanks!

But I did?
(To avoid having PRs blocked in the future, always include Signed-off-by: Author Name <authoremail@example.com> )

Or does it need to be literally `Signed-off-by: Author Name <authoremail@example.com>` ?

**Comment by MilanWR** [comment]
Signed-off-by: Author Name <authoremail@example.com>

**Comment by MilanWR** [comment]
AccountId.fromSolidityAddress is deprecated, use fromEvmAddress instead
Signed-off-by: Author Name [authoremail@example.com](mailto:authoremail@example.com)

**Comment by MilanWR** [comment]
AccountId.fromSolidityAddress is deprecated, use fromEvmAddress instead
Signed-off-by: Author Name [authoremail@example.com](mailto:authoremail@example.com)

**Pull request closed without merging**
