### PR TITLE
Update specialized-types.md 

### PR DESCRIPTION
**Pull request by MilanWR**
AccountId.fromSolidityAddress is deprecated, use fromEvmAddress instead
Signed-off-by: Author Name [authoremail@example.com](mailto:authoremail@example.com)

### CODE REVIEW

**Comment by MilanWR** [comment]
AccountId.fromSolidityAddress is deprecated, use fromEvmAddress instead
Signed-off-by: Author Name [authoremail@example.com](mailto:authoremail@example.com)

**Comment by MilanWR** [comment]
@theekrystallee please explain me what I need to do with this BS DCO. this is not beneficial for someone to contribute

**Comment by theekrystallee** [comment]
Hi @MilanWR, apologies for the inconvenience. As mentioned previously, the steps to resolve DCO are on [this page](https://github.com/hashgraph/hedera-docs/pull/684/checks?check_run_id=25247177301). I would suggest the "Rebase the branch" steps below if all else fails. Please let me know if you need further assistance. 

**Rebase the branch**
If you have a local git environment and meet the criteria below, one option is to rebase the branch and add your Signed-off-by lines in the new commits. Please note that if others have already begun work based upon the commits in this branch, this solution will rewrite history and may cause serious issues for collaborators ([described in the git documentation](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) under "The Perils of Rebasing").

You should only do this if:
- You are the only author of the commits in this branch
- You are certain nobody else is doing any work based upon this branch
- There are no empty commits in the branch (for example, a DCO Remediation Commit which was added using --allow-empty)

To add your Signed-off-by line to every commit in this branch:

1. Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
2. In your local branch, run: `git rebase HEAD~1 --signoff`
3. Force push your changes to overwrite the branch: `git push --force-with-lease origin patch-1`

**Comment by MilanWR** [comment]
thank you @theekrystallee , I really have no clue what this means. If it is so complicated to propose a simple change in the documentation I will refrain from further suggestions. Thank you.

**Comment by theekrystallee** [comment]
@MilanWR I understand your frustration and please continue contributing. The DCO sign-off is typically required when contributing to an open-source project. This is a minor PR so I can manually resolve and merge.

Thanks so much for your contributions!

**Review by theekrystallee — APPROVED** [review]
Thanks again for your contributions!

**Pull request merged**
